name: Release

on:
  push:
    branches:
      - stable
      - rc
      - beta
      - alpha

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: clone
  release:
    uses: shiipou/github-actions/.github/workflows/relearelease-branchesse.yml@main
    with:
      release-branches: stable
      download-artifacts: true
      assets: artifacts/clone/clone
