name: Release

on:
  push:
    branches:
      - stable
      - rc
      - beta
      - alpha

permissions:
  contents: write

jobs:
  release:
    uses: shiipou/github-actions/.github/workflows/release.yml@main
    with:
      release-branches: stable
      assets: clone
