name: Release

on:
  push:
    branches:
      - main
      - rc
      - beta
      - alpha

permissions:
  contents: write

jobs:
  get-version:
    uses: shiipou/github-actions/.github/workflows/get-version.yml@main
    with:
      release-branches: "^(main)$"
      prerelease-branches: "^(rc|beta|alpha)$"
  
  prepare-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./clone

  release:
    needs: get-version
    if: ${{ needs.get-version.outputs.will-release }}
    uses: shiipou/github-actions/.github/workflows/release.yml@main
    with:
      version: ${{ needs.get-version.outputs.version }}
      changelogs: ${{ needs.get-version.outputs.changelogs }}
      is-prerelease: ${{ needs.get-version.outputs.is-prerelease == 'true' }}
      download-artifacts: true
      assets: artifacts/clone
